# Generated by Django 4.2.27 on 2025-12-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarwashBooking', '0002_alter_bookingcostdetails_washer'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
